chatModel:
  model: "gpt-oss"
  base_url: "http://43.143.151.41:3000/v1"
  api_key: "sk-45jfj2wN89d0hwLFA18c71D7D3A3462b9eBe96F6Ea7d8cF5"
embeddingModel:
    model: "gpt-oss"
    base_url: "http://43.143.151.41:3000/v1"
    api_key: "sk-45jfj2wN89d0hwLFA18c71D7D3A3462b9eBe96F6Ea7d8cF5"
server:
  ip: 127.0.0.1
  port: 9000
database:
  type: "mysql"
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "123456"
  database: "deepseek"
  table: "chat_history"
