import { NextRequest, NextResponse } from "next/server";
import { Client } from "@elastic/elasticsearch";
import { z } from "zod";

/**
 * ES 连接：默认本机 9200，可用环境变量覆盖
 * 需要基本认证的话，给 ES_USERNAME / ES_PASSWORD
 */
const es = new Client({
  node: process.env.ES_NODE || "http://127.0.0.1:9200",
  auth:
    process.env.ES_USERNAME && process.env.ES_PASSWORD
      ? { username: process.env.ES_USERNAME, password: process.env.ES_PASSWORD }
      : undefined,
});

// 默认可选字段（你提供的全集）
const DEFAULT_INCLUDE_FIELDS: Record<string, string[]> = {
  snoopy: [
    "timestamp",
    "unixtime",
    "scene_id",
    "log_type",
    "user",
    "session_id",
    "working_dir",
    "full_command",
    "message",
    "uid",
    "sid",
    "tty",
    "cwd",
    "filename",
    "command",
  ],
  zeek_conn: [
    "ts",
    "uid",
    "id.orig_h",
    "id.orig_p",
    "id.resp_h",
    "id.resp_p",
    "proto",
    "service",
    "duration",
    "orig_bytes",
    "resp_bytes",
    "conn_state",
    "local_orig",
    "local_resp",
    "missed_bytes",
    "history",
    "orig_pkts",
    "orig_ip_bytes",
    "resp_pkts",
    "resp_ip_bytes",
    "tunnel_parents",
    "scene_id",
    "from",
  ],
  sysdig: ["message", "scene_id", "from"],
};

// 请求体校验
const BodySchema = z.object({
  index: z.string().min(1),
  // include 为“要保留”的字段。缺省时使用 DEFAULT_INCLUDE_FIELDS
  include: z
    .object({
      snoopy: z.array(z.string()).optional(),
      zeek_conn: z.array(z.string()).optional(),
      sysdig: z.array(z.string()).optional(),
    })
    .partial()
    .optional(),
  // 可选：把整个索引临时停收（静默 drop）
  pause: z.boolean().optional(),
});

export async function POST(req: NextRequest) {
  try {
    const body = await req.json();
    const { index, include, pause } = BodySchema.parse(body);

    // 1) 组装本次要“保留”的字段（没给则用默认）
    const effectiveInclude: Record<string, string[]> = {
      snoopy: include?.snoopy ?? DEFAULT_INCLUDE_FIELDS.snoopy,
      zeek_conn: include?.zeek_conn ?? DEFAULT_INCLUDE_FIELDS.zeek_conn,
      sysdig: include?.sysdig ?? DEFAULT_INCLUDE_FIELDS.sysdig,
    };

    // 2) 从“完整字段路径”推导：
    //    - 每个来源允许的“顶层字段”集合 allowTop[src]（如 "id.orig_h" -> 顶层 "id"）
    //    - 需要精剪的“子字段白名单” allowNested[src][top]（例如 { zeek_conn: { id: ["orig_h","orig_p","resp_h","resp_p"] } })
    const { allowTop, allowNested } = buildAllowMaps(effectiveInclude);

    // 3) 为该索引生成/覆盖专属 pipeline id
    const pipelineId = `fields-${sanitizeId(index)}`;

    // 4) 生成 processors
    const processors = pause
      ? [
          // 整索引静默停收（上游收到 2xx，不重试）
          { drop: { if: "true" } },
        ]
      : [
          {
            script: {
              lang: "painless",
              params: {
                allowTop,
                allowNested,
              },
              source: painlessPruneScript,
            },
          },
        ];

    // 5) PUT/覆盖 ingest pipeline
    await es.ingest.putPipeline({
      id: pipelineId,
      body: {
        description:
          "Per-index field include (and optional pause). Auto-generated by Next.js API.",
        processors,
        // NOTE: 若需 on_failure，可在此添加统一告警处理
      },
    });

    // 6) 把该索引的 final_pipeline 指向它
    await es.indices.putSettings({
      index,
      body: {
        index: {
          final_pipeline: pipelineId,
        },
      },
    });

    return NextResponse.json({
      ok: true,
      index,
      pipelineId,
      paused: !!pause,
      includeEffective: effectiveInclude,
      message: pause
        ? "Final pipeline set to DROP for this index (paused)."
        : "Final pipeline set with field-include rules.",
    });
  } catch (err: any) {
    const status = err?.statusCode || 500;
    return NextResponse.json(
      {
        ok: false,
        error: err?.message || "Unknown error",
        details: err?.meta?.body ?? undefined,
      },
      { status }
    );
  }
}

/** ------ Helpers ------ */

// 将索引名转成安全的 pipeline id 片段
function sanitizeId(s: string) {
  return s.toLowerCase().replace(/[^a-z0-9._-]+/g, "-").slice(0, 256);
}

function buildAllowMaps(include: Record<string, string[]>) {
  const allowTop: Record<string, string[]> = {};
  const allowNested: Record<string, Record<string, string[]>> = {};

  for (const [src, fields] of Object.entries(include)) {
    const tops = new Set<string>();
    const nested: Record<string, Set<string>> = {};

    for (const f of fields) {
      const parts = f.split(".");
      const top = parts[0];
      tops.add(top);

      if (parts.length >= 2) {
        const sub = parts[1]; // 只支持一层嵌套（已满足 zeek_conn 的 id.*）
        if (!nested[top]) nested[top] = new Set<string>();
        nested[top].add(sub);
      }
    }

    allowTop[src] = Array.from(tops);

    const nestedOut: Record<string, string[]> = {};
    for (const [top, subs] of Object.entries(nested)) {
      nestedOut[top] = Array.from(subs);
    }
    if (Object.keys(nestedOut).length > 0) {
      allowNested[src] = nestedOut;
    }
  }

  return { allowTop, allowNested };
}

/**
 * Painless：按来源裁剪字段
 * - 来源识别：优先 log_type，其次 from；"zeek" 归一为 "zeek_conn"
 * - 顶层裁剪：只保留 allowTop[src] 中的顶层字段
 * - 子字段裁剪：对 allowNested[src] 中列出的顶层对象，按白名单保留子字段
 *
 * 注意：这里只裁剪一层嵌套（已适配 zeek 的 "id.*"）
 */
const painlessPruneScript = String.raw`
String src = null;
if (ctx.containsKey('log_type')) {
  src = (String) ctx.log_type;
} else if (ctx.containsKey('from')) {
  src = (String) ctx.from;
}
if (src == 'zeek') { src = 'zeek_conn'; }

// 读取白名单
def topList = params.allowTop != null ? params.allowTop.get(src) : null;
if (topList == null) { return; }

// 顶层裁剪
def keep = new HashSet(topList);
def keys = new ArrayList(ctx.keySet());
for (def k : keys) {
  if (!keep.contains(k)) { ctx.remove(k); }
}

// 子字段裁剪（仅对列出的对象做）
def nestedMap = params.allowNested != null ? params.allowNested.get(src) : null;
if (nestedMap != null) {
  def entries = nestedMap.entrySet();
  for (def e : entries) {
    def top = e.getKey();
    def subs = new HashSet(e.getValue());
    if (ctx.containsKey(top) && ctx[top] instanceof Map) {
      def m = (Map) ctx[top];
      def subkeys = new ArrayList(m.keySet());
      for (def sk : subkeys) {
        if (!subs.contains(sk)) { m.remove(sk); }
      }
    }
  }
}
`;
