import { NextRequest, NextResponse } from "next/server";
import { Client } from "@elastic/elasticsearch";
import { z } from "zod";

const es = new Client({
  node: process.env.ES_NODE || "http://127.0.0.1:9200",
  auth:
    process.env.ES_USERNAME && process.env.ES_PASSWORD
      ? { username: process.env.ES_USERNAME, password: process.env.ES_PASSWORD }
      : undefined,
});

const DEFAULT_INCLUDE_FIELDS: Record<string, string[]> = {
  snoopy: [
    "timestamp",
    "unixtime",
    "scene_id",
    "log_type",
    "user",
    "session_id",
    "working_dir",
    "full_command",
    "message",
    "uid",
    "sid",
    "tty",
    "cwd",
    "filename",
    "command",
  ],
  zeek_conn: [
    "ts",
    "uid",
    "id.orig_h",
    "id.orig_p",
    "id.resp_h",
    "id.resp_p",
    "proto",
    "service",
    "duration",
    "orig_bytes",
    "resp_bytes",
    "conn_state",
    "local_orig",
    "local_resp",
    "missed_bytes",
    "history",
    "orig_pkts",
    "orig_ip_bytes",
    "resp_pkts",
    "resp_ip_bytes",
    "tunnel_parents",
    "scene_id",
    "from",
  ],
  sysdig: ["message", "scene_id", "from"],
};

const BodySchema = z.object({
  index: z.string().min(1),
  include: z
    .object({
      snoopy: z.array(z.string()).optional(),
      zeek_conn: z.array(z.string()).optional(),
      sysdig: z.array(z.string()).optional(),
    })
    .partial()
    .optional(),
  pause: z.boolean().optional(),
});

export async function POST(req: NextRequest) {
  try {
    const body = await req.json();
    const { index, include, pause } = BodySchema.parse(body);

    const effectiveInclude: Record<string, string[]> = {
      snoopy: include?.snoopy ?? DEFAULT_INCLUDE_FIELDS.snoopy,
      zeek_conn: include?.zeek_conn ?? DEFAULT_INCLUDE_FIELDS.zeek_conn,
      sysdig: include?.sysdig ?? DEFAULT_INCLUDE_FIELDS.sysdig,
    };

    const { allowTop, allowNested } = buildAllowMaps(effectiveInclude);

    const pipelineId = `fields-${sanitizeId(index)}`;

    const processors = pause
      ? [{ drop: { if: "true" } }]
      : [
          {
            script: {
              lang: "painless",
              params: {
                allowTop,
                allowNested,
              },
              source: painlessPruneScript,
            },
          },
        ];

    await es.ingest.putPipeline({
      id: pipelineId,
      body: {
        description:
          "Per-index field include (and optional pause). Auto-generated by Next.js API.",
        processors,
      },
    });

    await es.indices.putSettings({
      index,
      body: {
        index: {
          final_pipeline: pipelineId,
        },
      },
    });

    return NextResponse.json({
      ok: true,
      index,
      pipelineId,
      paused: !!pause,
      includeEffective: effectiveInclude,
      message: pause
        ? "Final pipeline set to DROP for this index (paused)."
        : "Final pipeline set with field-include rules.",
    });
  } catch (err: any) {
    const status = err?.statusCode || 500;
    return NextResponse.json(
      {
        ok: false,
        error: err?.message || "Unknown error",
        details: err?.meta?.body ?? undefined,
      },
      { status }
    );
  }
}

function sanitizeId(s: string) {
  return s.toLowerCase().replace(/[^a-z0-9._-]+/g, "-").slice(0, 256);
}

function buildAllowMaps(include: Record<string, string[]>) {
  const allowTop: Record<string, string[]> = {};
  const allowNested: Record<string, Record<string, string[]>> = {};

  for (const [src, fields] of Object.entries(include)) {
    const tops = new Set<string>();
    const nested: Record<string, Set<string>> = {};

    for (const f of fields) {
      const parts = f.split(".");
      const top = parts[0];
      tops.add(top);

      if (parts.length >= 2) {
        const sub = parts[1];
        if (!nested[top]) nested[top] = new Set<string>();
        nested[top].add(sub);
      }
    }

    allowTop[src] = Array.from(tops);

    const nestedOut: Record<string, string[]> = {};
    for (const [top, subs] of Object.entries(nested)) {
      nestedOut[top] = Array.from(subs);
    }
    if (Object.keys(nestedOut).length > 0) {
      allowNested[src] = nestedOut;
    }
  }

  return { allowTop, allowNested };
}

const painlessPruneScript = String.raw`
String src = null;
if (ctx.containsKey('log_type')) {
  src = (String) ctx.log_type;
} else if (ctx.containsKey('from')) {
  src = (String) ctx.from;
}
if (src == 'zeek') { src = 'zeek_conn'; }

def topList = params.allowTop != null ? params.allowTop.get(src) : null;
if (topList == null) { return; }

def keep = new HashSet(topList);
def keys = new ArrayList(ctx.keySet());
for (def k : keys) {
  if (!keep.contains(k)) { ctx.remove(k); }
}

def nestedMap = params.allowNested != null ? params.allowNested.get(src) : null;
if (nestedMap != null) {
  def entries = nestedMap.entrySet();
  for (def e : entries) {
    def top = e.getKey();
    def subs = new HashSet(e.getValue());
    if (ctx.containsKey(top) && ctx[top] instanceof Map) {
      def m = (Map) ctx[top];
      def subkeys = new ArrayList(m.keySet());
      for (def sk : subkeys) {
        if (!subs.contains(sk)) { m.remove(sk); }
      }
    }
  }
}
`;
